#!/bin/sh

# install script for unix-like systems
# its takes the installation path as an argument,
# builds the project and installs it in the passed directory
# example: ./install_nix /path/to/install

# check args
if [ "$#" -lt "1" ]; then
    echo "Install path required"
    exit 1
fi

install_path="$1"

cd ..
if [ -d "build" ]; then
    rm -r "build"
fi
mkdir -p "build"
cd "build"

# configure
cmake -DINSTALL_GMOCK:BOOL=OFF \
    -DCMAKE_INSTALL_PREFIX:PATH=$install_path ../

if [ $? -gt 1 ]; then
    echo "Error occured while generating cmake project's files"
fi

result=$(cmake --build . -j 6)

if [ $? -gt 1 ]; then
    echo "Error occured while building the project"
fi

# Install the project
make install/local
echo Project installed to $install_path
