.TH "ConverterJSON" 3 "Fri Oct 6 2023" "Search Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConverterJSON
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <converter_json\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConverterJSON\fP (const std::string &jsons_dir, bool recursive=false)"
.br
.ti -1c
.RI "\fBConverterJSON\fP (std::string path_first, std::string path_second)"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetRequests\fP () const"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetDocumentsPaths\fP () const"
.br
.ti -1c
.RI "int \fBgetResponsesLimit\fP () const"
.br
.ti -1c
.RI "void \fBputAnswers\fP (const std::vector< answer_t > &answers) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static json \fBopenJson\fP (const std::string &path)"
.br
.ti -1c
.RI "static int \fBwriteJsonToFile\fP (json &json_obj, const std::string &path)"
.br
.ti -1c
.RI "static std::string \fBfindFile\fP (const std::string &file_name, const std::string &dir='\&.', bool recursive=false)"
.br
.ti -1c
.RI "static void \fBprintJson\fP (const json &source)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for working with json files\&. Works like RAII 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConverterJSON::ConverterJSON (const std::string & jsons_dir, bool recursive = \fCfalse\fP)\fC [explicit]\fP"
Constructs converter with searching configuration files in jsons_dir 
.PP
\fBParameters\fP
.RS 4
\fIjsons_dir\fP path to search in 
.br
\fIrecursive\fP flag indicates how to search jsons 
.RE
.PP

.SS "ConverterJSON::ConverterJSON (std::string path_first, std::string path_second)"
Constructs converter from specified files, file order doesn't matter 
.PP
\fBParameters\fP
.RS 4
\fIpath_first\fP path to config | requests 
.br
\fIpath_second\fP path to config | requests 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::string ConverterJSON::findFile (const std::string & file_name, const std::string & dir = \fC'\&.'\fP, bool recursive = \fCfalse\fP)\fC [static]\fP"
Searches for file_name in current directory and in directories such as json, jsons, JSON, JSONS 
.PP
\fBParameters\fP
.RS 4
\fIfile_name\fP name of the file to find 
.br
\fIdir\fP directory where to search 
.br
\fIrecursive\fP flag indicates how to search file 
.RE
.PP
\fBReturns\fP
.RS 4
absolute path to a file or empty string 
.RE
.PP

.SS "std::vector< std::string > ConverterJSON::getDocumentsPaths () const"
Method for receiving path to docs from the config\&.json file 
.PP
\fBReturns\fP
.RS 4
a list with the paths to documents to search 
.RE
.PP

.SS "std::vector< std::string > ConverterJSON::getRequests () const"
Method for receiving requests from the requests\&.json file 
.PP
\fBReturns\fP
.RS 4
a list of requests from the requests\&.json file 
.RE
.PP

.SS "int ConverterJSON::getResponsesLimit () const"
The method reads the max_responses field to determine the limit number of responses per request 
.PP
\fBReturns\fP
.RS 4
max_responses 
.RE
.PP

.SS "json ConverterJSON::openJson (const std::string & path)\fC [static]\fP"
Creates json object from a file under path\&. Before creating check if file exists, perms to read and file's extension(must be *\&.json) 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP path to the file 
.RE
.PP
\fBReturns\fP
.RS 4
json object if open is successfully, empty json otherwise 
.RE
.PP

.SS "void ConverterJSON::printJson (const json & source)\fC [static]\fP"
Print content of specified json file to standard output\&. Structured fields prints in blue color, arrays in green, elems of array in cyan, regular fields in magenta 
.PP
\fBParameters\fP
.RS 4
\fIsource\fP file to print out 
.RE
.PP

.SS "void ConverterJSON::putAnswers (const std::vector< answer_t > & answers) const"
Method writes answers to the file answers\&.json 
.PP
\fBParameters\fP
.RS 4
\fIanswer\fP a data array containing answers to queries from the database of indexed documents 
.RE
.PP

.SS "int ConverterJSON::writeJsonToFile (json & json_obj, const std::string & path)\fC [static]\fP"
If file path exists overwriting it by file, create new file in path otherwise 
.PP
\fBParameters\fP
.RS 4
\fIfile\fP json to write 
.br
\fIpath\fP path to new file 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Search Engine from the source code\&.
