.TH "custom" 3 "Mon Oct 2 2023" "Search Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
custom
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBwordsCounter\fP (const std::string &s)"
.br
.ti -1c
.RI "std::string \fBgetFileName\fP (std::string s)"
.br
.ti -1c
.RI "size_t \fBcountOccurrences\fP (std::string_view text, const std::string &word)"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetUniqueWords\fP (const std::string &text)"
.br
.ti -1c
.RI "double \fBround\fP (double num, int precision)"
.br
.ti -1c
.RI "void \fBprint_red\fP (const std::string &msg)"
.br
.ti -1c
.RI "void \fBprint_green\fP (const std::string &msg)"
.br
.ti -1c
.RI "void \fBprint_yellow\fP (const std::string &msg)"
.br
.ti -1c
.RI "void \fBprint_blue\fP (const std::string &msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The namespace defines helper functions for string processing and text output 
.SH "Function Documentation"
.PP 
.SS "size_t custom::countOccurrences (std::string_view text, const std::string & word)"
Count occurrences of the word in text 
.PP
\fBParameters\fP
.RS 4
\fItext\fP text 
.br
\fIword\fP a word to count 
.RE
.PP
\fBReturns\fP
.RS 4
number of occurrences word in text 
.RE
.PP

.SS "std::string custom::getFileName (std::string s)"
Receives a path to a file or directory as input, returns its name example:s ='/project/logs/config\&.txt', getFileName(s) returns config\&.txt 
.PP
\fBParameters\fP
.RS 4
\fIs\fP path to file or directory 
.RE
.PP
\fBReturns\fP
.RS 4
the name of directory or file 
.RE
.PP

.SS "std::vector< std::string > custom::getUniqueWords (const std::string & text)"
The function generates a list of unique words from the text 
.PP
\fBParameters\fP
.RS 4
\fItext\fP string of one or more words 
.RE
.PP
\fBReturns\fP
.RS 4
list of unique words 
.RE
.PP

.SS "void custom::print_blue (const std::string & msg)"
Colors printing to standard output in blue 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP message to printWithFormatting 
.RE
.PP

.SS "void custom::print_green (const std::string & msg)"
Colors printing to standard output in green 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP message to printWithFormatting 
.RE
.PP

.SS "void custom::print_red (const std::string & msg)"
Сolors printing to standard output in red 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP message to printWithFormatting 
.RE
.PP

.SS "void custom::print_yellow (const std::string & msg)"
Colors printing to standard output in yellow 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP message to printWithFormatting 
.RE
.PP

.SS "double custom::round (double num, int precision)"
Rounds the number up to n decimal place 
.PP
\fBParameters\fP
.RS 4
\fInum\fP number to round 
.br
\fIprecision\fP quantity with decimal place 
.RE
.PP
\fBReturns\fP
.RS 4
rounded number 
.RE
.PP

.SS "size_t custom::wordsCounter (const std::string & s)"
Counts number of words in string 
.PP
\fBParameters\fP
.RS 4
\fIs\fP string 
.RE
.PP
\fBReturns\fP
.RS 4
number of words in string 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Search Engine from the source code\&.
