.TH "DocRelevance" 3 "Fri Oct 6 2023" "Search Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DocRelevance
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <search_server\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDocRelevance\fP (const std::pair< size_t, size_t > &pair)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBDocRelevance\fP &right) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBdoc_id\fP"
.br
.ti -1c
.RI "size_t \fBrelevance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for forming the relevance of documents 

.SH "Author"
.PP 
Generated automatically by Doxygen for Search Engine from the source code\&.
