.TH "format" 3 "Fri Oct 6 2023" "Search Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
format
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBunicode\fP"
.br
.ti -1c
.RI " \fButf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
namespace defines two other namespaces for formatting strings in the unicode and utf-8 encodings accordingly 
.SH "Author"
.PP 
Generated automatically by Doxygen for Search Engine from the source code\&.
