.TH "RelativeIndex" 3 "Wed Sep 27 2023" "Search Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RelativeIndex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <search_server\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBRelativeIndex\fP &other) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBdoc_id\fP"
.br
.ti -1c
.RI "double \fBrank\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure represents an relevant document and its relevance for the query 

.SH "Author"
.PP 
Generated automatically by Doxygen for Search Engine from the source code\&.
