.TH "ScreenWriter" 3 "Wed Sep 27 2023" "Search Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScreenWriter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScreenWriter\fP (ArgsList args)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class\&.\&.\&. Args> static ConverterPtr \fBmakeConverter\fP (Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "static ConverterPtr \fBhandMakeConverter\fP ()"
.br
.ti -1c
.RI "static ArgsList \fBcommandParser\fP (const std::string &cmd)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "ArgsList ScreenWriter::commandParser (const std::string & cmd)\fC [static]\fP"
Turns a string into a sequence of commands 
.PP
\fBParameters\fP
.RS 4
\fIcmd\fP string containing commands 
.RE
.PP
\fBReturns\fP
.RS 4
queue containing commands 
.RE
.PP

.SS "ConverterPtr ScreenWriter::handMakeConverter ()\fC [static]\fP"
An alternative way to construct \fBConverterJSON\fP through dialogue with the user 
.PP
\fBReturns\fP
.RS 4
unique_ptr to created \fBConverterJSON\fP 
.RE
.PP

.SS "template<class\&.\&.\&. Args> ConverterPtr ScreenWriter::makeConverter (Args &&\&.\&.\&. args)\fC [static]\fP"
Method constructs \fBConverterJSON\fP 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIArgs\fP variadic parameters 
.RE
.PP
\fBParameters\fP
.RS 4
\fIargs\fP arguments will be passed to the constructor \fBConverterJSON\fP can be (), (string), (string, string) 
.RE
.PP
\fBReturns\fP
.RS 4
unique_ptr to a ConverterJson
.RE
.PP
The method must be defined in the declaration file because it requires instantiation 

.SH "Author"
.PP 
Generated automatically by Doxygen for Search Engine from the source code\&.
