.TH "SearchServer" 3 "Fri Oct 6 2023" "Search Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SearchServer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <search_server\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSearchServer\fP (const \fBInvertedIndex\fP &idx)"
.br
.ti -1c
.RI "std::vector< answer_t > \fBsearch\fP (const std::vector< std::string > &queries_input)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class performs search for relevant documents 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SearchServer::SearchServer (const \fBInvertedIndex\fP & idx)\fC [inline]\fP, \fC [explicit]\fP"

.PP
\fBParameters\fP
.RS 4
\fIidx\fP reference to the docs dictionary 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::vector< answer_t > SearchServer::search (const std::vector< std::string > & queries_input)"
Search query processing method (async) 
.PP
\fBParameters\fP
.RS 4
\fIqueries_input\fP search queries taken from the file requests\&.json 
.RE
.PP
\fBReturns\fP
.RS 4
returns a sorted list of relevant responses for given requests 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Search Engine from the source code\&.
