.TH "Shell" 3 "Mon Oct 2 2023" "Search Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shell
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBoperator()\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCmd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Search Engine from the source code\&.
