#ifndef CUSTOM_LIMITS_H
#define CUSTOM_LIMITS_H

//Constants
#define MAX_WORDS_NUMBER 1000
#define MAX_WORD_LENGTH 100
#define MAX_REQUESTS_NUMBER 1000
#define MAX_REQUEST_WORDS_NUMBER 10

#endif //CUSTOM_LIMITS_H
